# 제로베이스 데이터 사이언스 스쿨 3기 SQL 과제 2
- 유가 데이터 분석

### 8문제 총 100점

- 1번 5점
- 2번 5점
- 3번 10점
- 4번 30점
- 5번 10점
- 6번 10점
- 7번 15점
- 8번 15점

### 1 ~ 8번 모두 본 노트북 파일에 답안 작성해서 제출해주세요 :)

---

문제 1.

주유소 데이터를 저장할 테이블을 다음의 구조로 생성하세요. (PDF 파일 참고)

문제 2.

Python 코드로 GAS_BRAND 데이터를 다음과 같이 입력하고 확인하세요. (PDF 파일 참고)

제출 1.
- Table 생성 결과 : Desc GAS_BRAND; Desc GAS_STATION;

제출 2.
- GAS_BRAND 조회 결과 : SELECT * FROM GAS_BRAND;

문제 3.

다음의 함수와 그 함수를 테스트하는 코드를 작성하세요. (PDF 파일 참고)

- 화폐단위 문자형을 입력받아 숫자형으로 반환하는 함수 (테스트 입력 : ‘1,000’)
- 주유소 브랜드를 입력하면 GAS_BRAND 데이터를 참고하여 ID 를 반환하는 함수 (테스트 입력 : ‘SK에너지’) - 주소를 입력받아 구 이름을 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)
- 주소를 입력받아 위도, 경도를 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)

제출 3.
- 각 함수 및 테스트 코드와 실행결과

문제 4.

Python 코드에서 주유소 페이지에서 데이터를 가져올때, GAS_STATION 테이블에 바로 입력하도록 수정하세요. (앞서 생 성한 함수활용)
- 주의. city 는 ‘서울’ 로 고정, 부가정보 데이터 타입
- 입력된 데이터의 총 갯수를 쿼리하여 결과를 확인합니다. - 입력된 데이터 상위 10개를 쿼리하여 결과를 확인합니다.


제출 4.
- 주유소 데이터 관련 코드 (ipynb)

문제 5.

시각화 프로젝트를 위하여 다음의 규칙으로 쿼리하여 CSV 파일로 저장합니다. (Python 코드로 작성)
- 전체 데이터를 가져오는데, 주유소 브랜드 아이디 대신 브랜드명이 표시되어야 합니다. (정렬 : 주유소 매장 아이디 순)
- 다음의 형식으로 저장되어야 함 (브랜드 이름, 칼럼 명 주의, id : GAS_STORE.id)

제출 5.
- 시각화 프로젝트 관련 코드 (ipynb), 결과 파일 (csv)

문제 6.

위도, 경도 정보를 이용하여 미왕빌딩에서 1킬로 이내에 위치한 주유소 정보를 검색하세요.

- 주유소 아이디, 주유소 브랜드명, 주유소 매장명, 주소, 미왕빌딩으로 부터의 거리 (km)

제출 6.
- 쿼리, 결과

문제 7.

위도, 경도 정보를 이용하여 미왕빌딩에서 셀프주유가 가능하고 24시간이면서 편의점이 있는 가장 가까운 주유소 10개를 휘 발유 가격이 가장 저렴한 순으로 정렬하여 조회하세요.

- 주유소 아이디, 주유소 브랜드명, 주유소 매장명, 주소, 휘발유 가격, 부가정보 (셀프, 24시간, 편의점 여부), 미왕빌딩으로 부터의 거리 (km)


제출 7.
- 쿼리, 결과

문제 8.

구별로 주유소 브랜드 별 휘발유 평균가격을 조회하여 저렴한 순으로 출력하세요.

- 구 이름, 주유소 브랜드 이름, 휘발유 평균 가격

제출 8.
- 쿼리, 결과

---